version: '3.8'

services:
  minio:
    image: minio/minio:latest
    container_name: datalake
    env_file:
      - .env
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - custom_net

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    env_file:
      - .env
    entrypoint: >
      /bin/sh -c "
      echo 'Waiting for MinIO...' && sleep 5;
      /usr/bin/mc alias set myminio http://minio:9000 $${MINIO_ROOT_USER} $${MINIO_ROOT_PASSWORD};
      /usr/bin/mc mb myminio/raw-data --ignore-existing;
      /usr/bin/mc mb myminio/processed-data --ignore-existing;
      /usr/bin/mc mb myminio/analytics-data --ignore-existing;
      "
    networks:
      - custom_net

  pipeline:
    build: .
    container_name: financial_data_pipeline
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    depends_on:
      createbuckets:
        condition: service_completed_successfully
    networks:
      - custom_net
    dns:
      - 8.8.8.8
      - 1.1.1.1

volumes:
  minio_data:

networks:
  custom_net:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1400