app:
  name: "Financial Data Analyzer"
  version: "1.0.0"
  env: "development"

paths:
  raw_data: "data/raw"
  processed_data: "data/processed"
  database: "data/analytics/financial_data.duckdb"
  models: "data/models"

ingestion:
  active_provider: 
  - "yfinance"
  - "bybit"

  targets:
    yfinance: 
    - "AAPL"
    - "GOOGL"
    - "MSFT"
    - "AMZN"
    - "TSLA"
    - "META"
    bybit:
    - "BTCUSDT"
    - "ETHUSDT"
    - "SOLUSDT"
    - "ADAUSDT"
    - "XRPUSDT"
    - "LTCUSDT"
    - "DOGEUSDT"
    - "DOTUSDT"
    - "AVAXUSDT"
    - "MATICUSDT"
    - "PEPUSDT "

  settings:
    start_date: "2012-01-01"

providers:
  yfinance:
    interval: "1h"
  
  bybit:
    category: "linear"
    interval: "60" # 60 for 1hr, D for daily, W for weekly
    limit: 1000


